language: java
jdk: openjdk11
deploy:
  provider: heroku
  api_key:
    secure: MBzWeRk1qS9UQoqhhFRso//H+Zo6G3jf1ooRima0PuGF7nXuZKNAV8c9yj7SfXwNrtm2LEm4pCKlq4BB/o1l/g/JwxjFkaBdET3VVAkD4eqnO3OTXeg52rAzmkW5FgbMXBDGNs7gMr7RzEAN8Z2EOCzjmcAxi0XZ6wD151MVijvdcyG4VyFW9HRPvNM1fP8yMmAiXmFgfY+z9tIXsuZJmk0RCCxzTHUFMJ7Ck0lK6tM9Uj3Be266KExrUzkNy8ai7Jh23JMy3ArE9OWckMPCn3QmIH54tYHzj0d7xHT+SCH7slldPF4C7grc38bOj9kPvkt472G5AZLV0OdF5pRlmCvHaXBvQhPLyY9WztgEf+C+8f5ex9uMkkhVInm2LS8XmW3oXcIjtbJkeGRz5I1a5jsaiucvf+HQclnJNVaab/WafcdEevn/+PIRIpe76ZOkrqUpLH5rbAZRwODZbbkT/s9wzjY/+buVFwqTzVcoJPGcqPE+wEdcwcB0TKNj8QOA6tTtgxehQkFmDzW87DWmwehCp4EWzs6ghuMXRyqOmYdxd1LKf9JNgnZGeFjoS5x3kBO4aubziHtsqjyOAEhjLQBssCc/GoeVz3ib4a+B+/tFQv2Ww85QV6ygjb0pU+cAMdcWHwGWDPyNjeU3EF+OixqgRmqaHa2HKqxjCroXRuM=
  skip_cleanup: true
  on:
    all_branches: true
