language: java
jdk: openjdk11
deploy:
  provider: heroku
  api_key:
    secure: fcM5nh22yvK0aFneerC8/uOL0wguTNveXNgL6GzazmRziPBB0xSfnve9s53nLqOYu6smzksp3/+z0XZ/kwEWhpuJie0UTscjuvZVbA+2wQD/Ic0L8xXW8shZTw4Y072/XvKmQpSshjAcT+R5x0W5rXc7jSdajiQeXyquIMgOU5cPx444sKcqibaN3ldrcwMUSI/MKnZXtjnR1IhbvJbVV5qMYeOxykSI+U1/4fBERlatfH0MqJqWcJHGgPZ8KfZXcvld2YRX+qjQCbfZNwStguzS2+Q38GpuR8AHdQZFqbdjBgc9bTszyYdOn303EGCUbAZJ1aH5oU6zeZMhxUdZTV8vvwKVaAM5GqcnujIEO6EREh30ASV+60lzbjXOfG0NioKqkm05aqL2ciJLskKRVHWLzP8KdyHTdeh1zy9YOuecRD0462PpYEnxhcj5Dj5ywdaIXOLU21EKHzJwmyBkbVkg91TdOU1cBTNw1DPGCA3r35K+sDkdV4mgOxH6hFO0oHo+XzaE+NhZNfxBTRcrZy9+EnR0DsMZQXS2rJeNqlbhM8tE24qToPPvJLvLShC/hKLYIVnQ2ppvw+Xu1L9n7osN+0ODkzJELd/hmwqP8/doikqQ+tYEquX9VjcsA/DD6eCvtFLfNx6g+cI+WCZNKSTwuPd4SXgrSEty/mBJALk=
  skip_cleanup: true