language: java
jdk: openjdk11

deploy:
  provider: heroku
  api_key:
    secure: "WDYwPCYaP+6PEA6a374pE8cYlJ7NBxelWjXds1QNxpbaNtvQDvVcLP4l5CjBG/sK8oKt/5AlPhN3x3HtrvA/LEg7piilr0a8plZEevzkhlg194R1QhYqfNnyUcbVwy1GgjpbbqmqUqMSh7X9RPUpeYAGqbMYRcsL1ghkpZ4BQ4jwsyEDfuwTb7IRsmCgyeNKKAuwOKAJWKaN1oGz8lzUn177Yv6JMr3pZBTDHy99oFIc1qz1YXJmz2pwLfWY74tYNnmVAFuMoyc8ANmx6QM+9MeRPziug3P2ElBRRA5NFV70VCGwy+bYmpqxf9Y8plE3xdjRy0M0Lbo+0zhU/BOHNV7BoOKDFAdyystpMbTALxychW7XEY4qPA3u1J29tEKndY4DNnwbzBLT+S0FlNFLtgfRBXC8pKt0GAFj7je/sKEJK2jiVts7XFQXwwhQgVketmHJHADrTx0XoqzwH67XuqkW/utyRIxmbt+QXxoU3Bdr6C3jM1Fw9q6bYrvhij7Q1R+43oX3r3Crk1ba0W8/j1qCLNG3aJxkn8EdZjBNIvOaUm5kGXRJan4VMp51ApQcd4Pq/LI6IaUdjWUvqxEYz95aHIO739iNgyDudNnwz54+VAD3mDpfP9lfPvTR3dvJx2SvIGSO3/CiJmh9Wma67vok2yWNOVHO50VvjVQ56jg="
  skip_cleanup: true