spotify:
  clientId:
  clientSecret:
  redirectUri:
  accessTokenUri: https://accounts.spotify.com/api/token
  userAuthorizationUri: https://accounts.spotify.com/authorize
  scope: user-read-email,playlist-read-private,user-read-private
  showDialog: false